$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: distributed-llm-training-env
version: "1.2"
description: "Optimized environment for distributed LLM model training with latest ML frameworks"

# Base image with CUDA support
image: mcr.microsoft.com/azureml/curated/pytorch-2.0-cuda11.7-py38-ubuntu20.04:latest

# Conda environment specification
conda_file: |
  name: distributed-llm-training
  channels:
    - conda-forge
    - pytorch
    - nvidia
    - huggingface
  dependencies:
    - python=3.9
    - pip=23.0
    
    # Core ML frameworks
    - pytorch::pytorch=2.1.0
    - pytorch::torchvision=0.16.0
    - pytorch::torchaudio=2.1.0
    - pytorch::pytorch-cuda=11.8
    - cudatoolkit=11.8
    
    # HuggingFace ecosystem
    - transformers=4.36.0
    - datasets=2.14.0
    - tokenizers=0.15.0
    - accelerate=0.25.0
    
    # Training optimizations
    - deepspeed=0.12.0
    - fairscale=0.4.13
    
    # Data processing
    - numpy=1.24.0
    - pandas=2.1.0
    - scikit-learn=1.3.0
    - scipy=1.11.0
    
    # Computer vision
    - pillow=10.0.0
    - opencv=4.8.0
    - timm=0.9.0
    
    # Utilities
    - tqdm=4.66.0
    - rich=13.7.0
    - loguru=0.7.0
    
    # Development tools
    - jupyter=1.0.0
    - ipython=8.17.0
    - pytest=7.4.0
    
    # Pip dependencies
    - pip:
      # Azure integrations
      - azure-ai-ml==1.12.0
      - azure-storage-blob==12.19.0
      - azureml-core==1.54.0
      - azureml-mlflow==1.54.0
      
      # Experiment tracking
      - mlflow==2.9.0
      - wandb==0.16.0
      - tensorboard==2.15.0
      
      # PEFT techniques
      - peft==0.7.0
      - bitsandbytes==0.41.0
      - loralib==0.1.2
      
      # Model optimization
      - onnx==1.15.0
      - onnxruntime-gpu==1.16.0
      - optimum==1.15.0
      
      # Math and utilities
      - einops==0.7.0
      - safetensors==0.4.0
      - sentencepiece==0.1.99
      - protobuf==4.25.0
      
      # Code analysis
      - tree-sitter==0.20.0
      - tree-sitter-python==0.20.0
      - tree-sitter-javascript==0.20.0
      
      # Monitoring
      - prometheus-client==0.19.0
      - psutil==5.9.0
      
      # Networking
      - fastapi==0.104.0
      - uvicorn==0.24.0
      - httpx==0.25.0
      - aiofiles==23.2.0
      
      # Type checking and linting
      - mypy==1.7.0
      - black==23.11.0
      - ruff==0.1.6

tags:
  framework: pytorch
  cuda_version: "11.8"
  python_version: "3.9"
  use_case: training